CREATE TABLE IF NOT EXISTS USERS (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS STUDY_GROUPS (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    CODE VARCHAR(10) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS USER_GROUPS (
    USER_ID INT REFERENCES USERS(ID),
    GROUP_ID INT REFERENCES STUDY_GROUPS(ID),
    ROLE VARCHAR(20) DEFAULT 'member',
    PRIMARY KEY (USER_ID, GROUP_ID)
);