apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ghcr.io/imancheema/collabspace-backend:sha-dd5057a
          ports:
            - containerPort: 5000 #Express
            - containerPort: 6001 #Hocuspocus
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: postgres-password
            - name: DATABASE_URL
              value: "postgres://postgres:$(POSTGRES_PASSWORD)@db:5432/collabspace"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: jwt-secret
            - name: SPACES_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: spaces-key
            - name: SPACES_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: spaces-secret
            - name: SPACES_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: spaces-endpoint
            - name: SPACES_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: spaces-bucket
            - name: SPACES_REGION
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: spaces-region
            - name: FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: frontend-url
            - name: COLLAB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: collab-port
            - name: EXPRESS_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: express-port
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
    - name: websocket
      protocol: TCP
      port: 6001
      targetPort: 6001